// Generated by CoffeeScript 1.7.1
(function() {
  define(["jquery", "underscore", "backbone", "d3"], function($, _, Backbone, d3) {
    return Backbone.View.extend({
      el: "#states",
      events: {
        "change select": "change"
      },
      template: _.template("<select><% _.each(states, function(state) { %> <option val='<%state%>'><%=state%></option><% }); %></select>"),
      getCensus: function(cb) {
        return $.get("http://localhost:5000/census").success(function(data) {
          return cb(JSON.parse(data));
        });
      },
      initialize: function() {
        return getCensus(_.bind(function(census) {
          this.census = census;
          return this.render();
        }, this));
      },
      render: function() {
        var states;
        states = _.keys(this.census["2008"]);
        return this.$el.html(this.template({
          states: states
        }));
      },
      change: function() {
        return console.log(this.$("select").val());
      }
    });
  });

}).call(this);
